---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: server

resources:
  -  deployment.yaml
  -  namespace.yaml
  -  network-policy.yaml
  -  service.yaml

components:
  - ../components/default-network-policy
